#include "config.h"

float MIN_TEMPERATURE = 57.5;
float MAX_TEMPERATURE = 62.5;

float PUMP_ON = 62.7;
float PUMP_OFF = 57.7;

// ENERGY CONSUMPTION VARIABLES in WATTS
float RESISTANCE_CONSUMPTION = 3200;
float PUMP_CONSUMPTION = 1000;