#ifndef SRC_CONFIG
#define SRC_CONFIG

#include <Arduino.h>

// ENVIRONMENT
#define DEV false

// DEBUG
#define DEBUG true
#define DEBUG_RATIO 360
#define SERIAL_DEBUG false

// NETWORK
#define WIFI_SSID "BoxxComms"
#define WIFI_PASSWORD "01614287523"

#define WIFI_SSID_DEV "UPC2703909"
#define WIFI_PASSWORD_DEV "nxkVF7ksvt8j"

// #define WIFI_SSID_DEV "UPC3404214"
// #define WIFI_PASSWORD_DEV "Y66aedjtudhw"

#define MQTT_PUBLISH_INTERVAL 1000
#define MQTT_DATABASE_PUBLISH_INTERVAL 60000

// ESP PINS
#define BUZZER_PIN 13
#define RESISTANCE_PIN 5
#define PUMP_PIN 4

// THERMOCOUPLE PINS
#define MAX_CLK 14
#define MAX_CS 0
#define MAX_MISO 12 // DO

// TEMPERATURE VARIABLES
extern float MIN_TEMPERATURE;
extern float MAX_TEMPERATURE;
extern float PUMP_ON_TEMPERATURE;
extern float PUMP_OFF_TEMPERATURE;

// ENERGY CONSUMPTION VARIABLES
extern float RESISTANCE_CONSUMPTION;
extern float PUMP_CONSUMPTION;

// SCREEN VARIABLES
#define GREEN 960
#define RED 47169
#define BLUE 343
#define SKYBLUE 42654
#define SALMON 64073
#define ORANGE 62961
#define LIGHTGREEN 38706

#define RESISTANCE_OFF_PIC 84
#define PUMP_OFF_PIC 80

#define ARROW_UP_PIC 85
#define ARROW_DOWN_PIC 86

#define Screen Serial1

// MISCELLANEOUS
#define MESSAGE_NOT_DISPLAYED 0
#define MESSAGE_DISPLAYED 1

#define CYCLE_BEEP_AMOUNT 3
#define TERM_BEEP_AMOUNT 1

#define JSON_BUFFER_SIZE 512

#endif /* SRC_CONFIG */
