#include "config.h"

float MIN_TEMPERATURE = 57.5;
float MAX_TEMPERATURE = 62.5;

float PUMP_ON_TEMPERATURE = 62.7;
float PUMP_OFF_TEMPERATURE = 57.7;

// ENERGY CONSUMPTION VARIABLES in WATTS
//! TODO: Change these values to the real ones
float RESISTANCE_CONSUMPTION = 3200;
float PUMP_CONSUMPTION = 1000;